name: Build Image

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch dockerfile
        uses: actions/checkout@v3
        with:
          repository: zleetch/dockerfile
          path: docker
          ref: main
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
      - name: Build & Push docker image
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          file: docker/rust/Dockerfile
          build-args: app_name=server
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
      - name: Generate artifacts attestations
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
